loader="uefi"
graphics="yes"
graphics_res="1280x720"
graphics_listen="127.0.0.1"
xhci_mouse="yes"
cpu=4
#cpu_sockets=2
#cpu_cores=4
#cpu_threads=1
memory=4G

# Passthru; check using sudo vm passthru
#passthru2="6/0/0" # GPU

# Put up to 8 disks on a single ahci controller.
# without this, adding a disk pushes the following network devices onto higher slot numbers,
# which causes windows to see them as a new interface
ahci_device_limit="8"

# Main Windows OS Virtual Disk (File-backed disk image)
disk0_type="ahci-hd"
disk0_name="disk0.img"

# While e1000 network adapter works out-of-the-box and allowing the guest to get network access,
# it is rocommended to use virtio-net. To install drivers in the guest download virtio-net from
# https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso
# and install it into guest.
#network0_type="e1000"
network0_type="virtio-net"
network0_switch="public"

# One way to to install virtio-net is to boot in the install mode
# and specifying iso file.
disk1_type="ahci-cd"
disk1_dev="custom"
disk1_name="/path/to/virtio-win-x.x.x.x.iso"

# Physical SD Card Passthrough via Raw Block Device
# WARNING: Ensure the card is unmounted on the host (`umount /dev/da0s1`)
# before starting the VM to prevent data corruption.
#disk2_type="virtio-blk"
#disk2_dev="custom"
#disk2_name="/dev/da0"

# windows expects the host to expose localtime by default, not UTC
utctime="no"
