kern.geom.label.disk_ident.enable="0"
kern.geom.label.gptid.enable="0"
cryptodev_load="YES"
zfs_load="YES"

# PCI passthrough (bhyve)
pptdevs="0/20/0" # Give the USB controller (0/20/0; address of the USB controller) to Bhyve instead of FreeBSD
